name: Sonarqube pipeline

on:
  pull_request:
    branches: ["main"]

jobs:
  sonarqube:
    runs-on: ["Devops-Learning01"]

    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Sonarqube analysis
        uses: SonarSource/sonarqube-scan-action@v8.2.2
        with:
          args: >
            -Dsonar.projectKey=NodeApp
            -Dsonar.sources=.
            -Dsonar.host.url=http://localhost:9000
            -Dsonar.token=sqp_a706d8e5e8a17306a6da5d24939cc76cd9474a05
