name: Sonarqube pipeline

on:
  pull_request:
    branches: ["main"]

jobs:
  sonarqube:
    runs-on: ["Devops-Learning01"]

    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Sonarqube analysis
        uses: SonarSource/sonarqube-scan-action@v8.2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=NodeApp
            -Dsonar.sources=.
